/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios01;

/**
 *
 * @author Programacion Java
 */
public class Espejo extends javax.swing.JFrame {

    /**
     * Creates new form Espejo
     */
    public Espejo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        chk5 = new javax.swing.JCheckBox();
        cmbEspejo = new javax.swing.JComboBox<>();
        chk6 = new javax.swing.JCheckBox();
        spnEspejo = new javax.swing.JSpinner();
        txtOriginal = new javax.swing.JTextField();
        rbn1Espejo = new javax.swing.JRadioButton();
        cmbOriginal = new javax.swing.JComboBox<>();
        rbn2Espejo = new javax.swing.JRadioButton();
        rbn3Espejo = new javax.swing.JRadioButton();
        spnOriginal = new javax.swing.JSpinner();
        chk4Espejo = new javax.swing.JCheckBox();
        rbn1 = new javax.swing.JRadioButton();
        rbn2 = new javax.swing.JRadioButton();
        chk5Espejo = new javax.swing.JCheckBox();
        rbn3 = new javax.swing.JRadioButton();
        chk6Espejo = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        txtEspejo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chk5.setText("Opcion 5");
        chk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk5ActionPerformed(evt);
            }
        });

        cmbEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEspejo.setEnabled(false);

        chk6.setText("Opcion 6");
        chk6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk6ActionPerformed(evt);
            }
        });

        spnEspejo.setEnabled(false);

        txtOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOriginalKeyReleased(evt);
            }
        });

        buttonGroup2.add(rbn1Espejo);
        rbn1Espejo.setText("Opcion 1");
        rbn1Espejo.setEnabled(false);
        rbn1Espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn1EspejoActionPerformed(evt);
            }
        });

        cmbOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOriginalActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbn2Espejo);
        rbn2Espejo.setText("Opcion 2");
        rbn2Espejo.setEnabled(false);
        rbn2Espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn2EspejoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbn3Espejo);
        rbn3Espejo.setText("Opcion 3");
        rbn3Espejo.setEnabled(false);
        rbn3Espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn3EspejoActionPerformed(evt);
            }
        });

        spnOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnOriginalStateChanged(evt);
            }
        });

        chk4Espejo.setText("Opcion 4");
        chk4Espejo.setEnabled(false);

        buttonGroup1.add(rbn1);
        rbn1.setText("Opcion 1");
        rbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbn2);
        rbn2.setText("Opcion 2");
        rbn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn2ActionPerformed(evt);
            }
        });

        chk5Espejo.setText("Opcion 5");
        chk5Espejo.setEnabled(false);

        buttonGroup1.add(rbn3);
        rbn3.setText("Opcion 3");
        rbn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbn3ActionPerformed(evt);
            }
        });

        chk6Espejo.setText("Opcion 6");
        chk6Espejo.setEnabled(false);

        chk4.setText("Opcion 4");
        chk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk4ActionPerformed(evt);
            }
        });

        txtEspejo.setEnabled(false);

        jLabel1.setText("Original");

        jLabel2.setText("Espejo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbn1Espejo)
                            .addComponent(rbn2Espejo)
                            .addComponent(rbn3Espejo))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk4Espejo)
                            .addComponent(chk5Espejo)
                            .addComponent(chk6Espejo))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEspejo)
                            .addComponent(cmbEspejo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbn1)
                            .addComponent(rbn2)
                            .addComponent(rbn3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk4)
                            .addComponent(chk5)
                            .addComponent(chk6))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOriginal)
                            .addComponent(cmbOriginal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn1)
                    .addComponent(chk4)
                    .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn2)
                    .addComponent(chk5)
                    .addComponent(cmbOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn3)
                    .addComponent(chk6)
                    .addComponent(spnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn1Espejo)
                    .addComponent(chk4Espejo)
                    .addComponent(txtEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn2Espejo)
                    .addComponent(chk5Espejo)
                    .addComponent(cmbEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn3Espejo)
                    .addComponent(chk6Espejo)
                    .addComponent(spnEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbn1EspejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn1EspejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn1EspejoActionPerformed

    private void rbn2EspejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn2EspejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn2EspejoActionPerformed

    private void rbn3EspejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn3EspejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbn3EspejoActionPerformed

    private void rbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn1ActionPerformed
        // TODO add your handling code here:
        rbn1Espejo.setSelected(true);
    }//GEN-LAST:event_rbn1ActionPerformed

    private void rbn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn2ActionPerformed
        // TODO add your handling code here:
        rbn2Espejo.setSelected(true);
    }//GEN-LAST:event_rbn2ActionPerformed

    private void rbn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbn3ActionPerformed
        // TODO add your handling code here:
        rbn3Espejo.setSelected(true);
    }//GEN-LAST:event_rbn3ActionPerformed

    private void chk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk4ActionPerformed
        // TODO add your handling code here:
        if (chk4.isSelected()) {
            chk4Espejo.setSelected(true);
        }
        else {
            chk4Espejo.setSelected(false);
        } 
    }//GEN-LAST:event_chk4ActionPerformed

    private void chk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk5ActionPerformed
        // TODO add your handling code here:
        chk5Espejo.setSelected(true);
    }//GEN-LAST:event_chk5ActionPerformed

    private void txtOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyReleased
        // TODO add your handling code here:
        txtEspejo.setText(txtOriginal.getText());
    }//GEN-LAST:event_txtOriginalKeyReleased

    private void chk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk6ActionPerformed
        // TODO add your handling code here:
        chk6Espejo.setSelected(true);
    }//GEN-LAST:event_chk6ActionPerformed

    private void cmbOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOriginalActionPerformed
        // TODO add your handling code here:
        cmbEspejo.setSelectedIndex(cmbOriginal.getSelectedIndex());
    }//GEN-LAST:event_cmbOriginalActionPerformed

    private void spnOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnOriginalStateChanged
        // TODO add your handling code here:
        spnEspejo.setValue(spnOriginal.getValue());
    }//GEN-LAST:event_spnOriginalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espejo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk4Espejo;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk5Espejo;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk6Espejo;
    private javax.swing.JComboBox<String> cmbEspejo;
    private javax.swing.JComboBox<String> cmbOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbn1;
    private javax.swing.JRadioButton rbn1Espejo;
    private javax.swing.JRadioButton rbn2;
    private javax.swing.JRadioButton rbn2Espejo;
    private javax.swing.JRadioButton rbn3;
    private javax.swing.JRadioButton rbn3Espejo;
    private javax.swing.JSpinner spnEspejo;
    private javax.swing.JSpinner spnOriginal;
    private javax.swing.JTextField txtEspejo;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
